[PHP] improving php CS
green-code-initiative/ecoCode-php-test-project pull request #2
Opened 2023-06-01 14:46 UTC by JB-Ginguene

2023-06-01 17:21 UTC, utarwyn reviewed
I think reviews I have made in https://github.com/green-code-initiative/ecoCode/pull/197 are also relevants in this PR :+1:

2023-06-02 16:50 UTC, dedece35 requested changes

2023-06-02 16:50 UTC, dedece35 commented on src/AvoidUsingGlobalVariablesCheck.php
> +function somme() { // NOK {{Prefer local variables to globals}}
the error message is at wrong place ... if you check in real environment with your local SonarQube, you will see that the error is placed at line 7 (like before your commit)

2023-06-02 16:50 UTC, dedece35 commented on src/AvoidTryCatchFinallyCheck_NOK_FailsAllTryStatements.php
> +try { // NOK {{Avoid using try-catch}}
the error message is at wrong place ... if you check in real environment with your local SonarQube, you will see that the error is placed at line 15 (like before your commit)

2023-06-06 14:10 UTC, dedece35 commented on src/AvoidGettingSizeCollectionInLoop.php
in this file, all Non Compliant messages are at wrong position ... they should be positionned on the last "}" and not at the beginning of the loop.
could you please modify them, please ?

2023-06-06 17:22 UTC, dedece35 approved these changes

2023-06-06 17:22 UTC, merged